// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPNHNb0JbPyuNycNtm1s-dh3YfH8QyieM',
    appId: '1:953406452006:web:bf3691a257457e1ad591e7',
    messagingSenderId: '953406452006',
    projectId: 'smartkmcapp',
    authDomain: 'smartkmcapp.firebaseapp.com',
    storageBucket: 'smartkmcapp.firebasestorage.app',
    measurementId: 'G-0R7PFTLDRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsUebg_FhlO6RE7peMLwlUmDLg32GOhK0',
    appId: '1:953406452006:android:582a89df8ac2fbf3d591e7',
    messagingSenderId: '953406452006',
    projectId: 'smartkmcapp',
    storageBucket: 'smartkmcapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATB7OcTF5LpHJwyM9vljP0Fus8Zg6KlQs',
    appId: '1:953406452006:ios:b7cc0648ae24afecd591e7',
    messagingSenderId: '953406452006',
    projectId: 'smartkmcapp',
    storageBucket: 'smartkmcapp.firebasestorage.app',
    iosBundleId: 'com.example.smartKangarooMotherCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATB7OcTF5LpHJwyM9vljP0Fus8Zg6KlQs',
    appId: '1:953406452006:ios:b7cc0648ae24afecd591e7',
    messagingSenderId: '953406452006',
    projectId: 'smartkmcapp',
    storageBucket: 'smartkmcapp.firebasestorage.app',
    iosBundleId: 'com.example.smartKangarooMotherCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPNHNb0JbPyuNycNtm1s-dh3YfH8QyieM',
    appId: '1:953406452006:web:fa59fe13675ca741d591e7',
    messagingSenderId: '953406452006',
    projectId: 'smartkmcapp',
    authDomain: 'smartkmcapp.firebaseapp.com',
    storageBucket: 'smartkmcapp.firebasestorage.app',
    measurementId: 'G-L5048WSV51',
  );
}
